// Game Constants

export const GAME_CONFIG = {
  BASE_ANSWER_SPEED: 1.2,
  SPEED_INCREMENT: 0.3,
  MAX_SPEED_MULTIPLIER: 2.5,
  PROJECTILE_SPEED: 15,
  CORRECT_ANSWERS_PER_LEVEL: 10,
  INITIAL_LIVES: 3,
  STARSHIP_WIDTH: 60,
  STARSHIP_HEIGHT: 50,
  ANSWER_BLOCK_WIDTH: 80,
  ANSWER_BLOCK_HEIGHT: 50,
  PROJECTILE_WIDTH: 6,
  PROJECTILE_HEIGHT: 20,
  LEVEL_UP_DELAY: 2000,
};

export const COLORS = {
  SPACE_BLACK: '#0a0a1a',
  PRIMARY_BLUE: '#00d4ff',
  PRIMARY_GREEN: '#00ff88',
  PRIMARY_PURPLE: '#b44aff',
  WARNING_RED: '#ff4757',
  WARNING_ORANGE: '#ffa502',
  TEXT_WHITE: '#ffffff',
  TEXT_GRAY: '#a0a0a0',
  ANSWER_BG: '#2a2a4a',
  ANSWER_BORDER: '#4a4a7a',
};
